5 acceptance testing
wowmeow/QnA pull request #3
Opened 2021-08-15 17:57 UTC by wowmeow

2021-08-16 08:45 UTC, VidgarVii requested changes

2021-08-16 08:45 UTC, VidgarVii commented on spec/controllers/answers_controller_spec.rb
> +    end
не хватает сценария для неаутентифицированного юзера

2021-08-16 08:45 UTC, VidgarVii commented on spec/features/question/index_spec.rb
> +  end
не хватает сценария для неаутентифицированного юзера

2021-08-16 08:45 UTC, VidgarVii commented on spec/features/question/show_spec.rb
> +  end
не хватает сценария для неаутентифицированного юзера

2021-08-16 08:45 UTC, VidgarVii commented on spec/features/question/show_spec.rb
> +    answers.each do |answer|
итерации в тестах всегда плохо.
Если тест упадёт внутри блока, то сложно будет узнать, что именно упало
можно просто написать проверку на наличие текста, и сразу указать, что он встречается 3 раза

2021-08-16 08:45 UTC, VidgarVii commented on spec/features/answer/destroy_spec.rb
> +      expect(page).to_not have_content answer.title
в фича-тестах на удаление вопроса /ответа перед удалением хорошо бы добавить проверку, что удаляемый текст есть на странице, чтобы избежать ложно-положительного теста

2021-08-16 08:46 UTC, VidgarVii commented on spec/models/user_spec.rb
> +      expect(user).to_not be_author_of(question)
not_to

2021-08-16 14:47 UTC, wowmeow commented on spec/controllers/answers_controller_spec.rb
> +    end
Не поняла, как он должен в случае тестов для контроллера выглядеть

2021-08-16 17:24 UTC, VidgarVii commented on spec/features/question/show_spec.rb
> +    end
1 не исправила. https://github.com/wowmeow/QnA/pull/3#discussion_r689346057
чей текст тут тестируется?
2 Тестировать ответы на странице надо в папке answer. Ведь она отвечает за тесты ответов. А тут нужны тесты только за пользовательские действия с вопросами.

2021-08-16 17:24 UTC, VidgarVii commented on spec/features/question/show_spec.rb
> +feature 'User can view the question with answers', "
файлы в фича-тестах не обязательно называть по названию экшенов в контроллере. 
Фича тесты это не тестирование контроллеров. Тут описываются возможные пользовательские действия на странице. Это более высокий уровень абстракции. Тут работаем только с UI страницы

2021-08-16 17:24 UTC, VidgarVii commented on spec/models/user_spec.rb
> +    it 'false if user is not the author of question' do
как правило вохможные варианты это контекст.
context 'when user is the author'
context 'when user is not the author'

2021-08-16 18:19 UTC, wowmeow commented on spec/features/question/show_spec.rb
> +    end
1. Текст вопроса (title и body). Из #3 (comment) : 
> можно просто написать проверку на наличие текста, и сразу указать, что он встречается 3 раза

Я поняла, что вместо have_content нужно использовать алиас have_text и писать напрямую ожидаемые значения title и body этих вопросов. Если я исправила неверно, то не совсем понимаю, что ожидается вместо этого:

```
    expect(page).to have_text('Question title').exactly(3).times
    expect(page).to have_text('Question text').exactly(3).times
```

2021-08-16 18:26 UTC, wowmeow commented on spec/features/question/show_spec.rb
> +    end
Единственный вопрос: 
Как стоит назвать такой тест: index_spec или как-то иначе?

2021-08-16 18:28 UTC, wowmeow commented on spec/features/question/show_spec.rb
> +feature 'User can view the question with answers', "
Хорошо, в следующие разы буду более конкретно называть тесты

2021-08-17 07:44 UTC, VidgarVii commented on spec/features/question/show_spec.rb
> +    end
display question

2021-08-17 10:54 UTC, merged